# Generated by Django 5.2.4 on 2026-05-30 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_student_departments(apps, schema_editor):
    Student = apps.get_model('api', 'Student')
    Department = apps.get_model('api', 'Department')
    for student in Student.objects.all():
        name = (student.department_old or 'General').strip()
        code = ''.join(c for c in name.upper() if c.isalnum())[:20] or 'GEN'
        dept, _ = Department.objects.get_or_create(
            name=name,
            defaults={'code': code},
        )
        student.department_new_id = dept.id
        student.save(update_fields=['department_new'])


def reverse_migrate_student_departments(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='uploads/assignments/')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='api_book_created_7c2a71_idx',
            old_name='api_book_created_9c3d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='api_book_author_4fb1bd_idx',
            old_name='api_book_author_2f5a6b_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='api_student_departm_0cf16a_idx',
            old_name='api_student_departm_8a1f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='api_student_created_4c478b_idx',
            old_name='api_student_created_4b2e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='supportrequest',
            new_name='api_support_status_6ba317_idx',
            old_name='api_support_status_7e8f9a_idx',
        ),
        migrations.RenameIndex(
            model_name='supportrequest',
            new_name='api_support_created_ed744b_idx',
            old_name='api_support_created_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='supportrequest',
            new_name='api_support_student_7f7a81_idx',
            old_name='api_support_student_4d5e6f_idx',
        ),
        migrations.AddField(
            model_name='assignment',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='api.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.department'),
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='api_student_departm_0cf16a_idx',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='department_old',
        ),
        migrations.AddField(
            model_name='student',
            name='department_new',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='students_new',
                to='api.department',
            ),
        ),
        migrations.RunPython(migrate_student_departments, reverse_migrate_student_departments),
        migrations.RemoveField(
            model_name='student',
            name='department_old',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='department_new',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='students',
                to='api.department',
            ),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='api_student_departm_fk_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course'], name='api_student_course__be3ea1_idx'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='api.department'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_groups', to='api.course'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_groups', to='api.department'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='study_groups', to='api.student'),
        ),
        migrations.AddField(
            model_name='note',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='notes', to='api.studygroup'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='groups',
            field=models.ManyToManyField(related_name='assignments', to='api.studygroup'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'code')},
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['department', 'course'], name='api_studygr_departm_12bfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-created_at'], name='api_note_created_8b5593_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['-created_at'], name='api_assignm_created_e54e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='api_assignm_due_dat_1a77eb_idx'),
        ),
    ]
